# Generated by Django 3.1.2 on 2020-10-27 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seedbox',
            options={'verbose_name_plural': 'Seedboxes'},
        ),
    ]
