# Generated by Django 3.1.2 on 2020-10-27 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_auto_20201026_2242'),
    ]

    operations = [
        migrations.AddField(
            model_name='seedbox',
            name='login',
            field=models.CharField(default='admin', max_length=100),
        ),
        migrations.AddField(
            model_name='seedbox',
            name='password',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='seedbox',
            name='port',
            field=models.FloatField(default=8080),
        ),
    ]
