# Generated by Django 3.1.2 on 2020-11-10 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_device_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='type',
            field=models.CharField(default='Local', max_length=20),
        ),
    ]
