# Generated by Django 3.1.2 on 2020-11-10 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_auto_20201109_2240'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='password',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='device',
            name='user',
            field=models.CharField(default='', max_length=20),
        ),
    ]
