# Generated by Django 3.1.2 on 2020-11-11 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_auto_20201110_2216'),
    ]

    operations = [
        migrations.CreateModel(
            name='Moving',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
