# Generated by Django 3.1.2 on 2020-11-12 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0007_moving'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='moving',
            options={'verbose_name_plural': 'Moving'},
        ),
    ]
