# Generated by Django 3.1.2 on 2020-11-12 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0009_torrent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Moved',
        ),
        migrations.DeleteModel(
            name='Moving',
        ),
        migrations.AddField(
            model_name='movequeue',
            name='status',
            field=models.CharField(default='queued', max_length=10),
        ),
    ]
