# Generated by Django 3.1.2 on 2020-11-12 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0010_auto_20201112_1647'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movequeue',
            name='category',
        ),
        migrations.RemoveField(
            model_name='movequeue',
            name='client',
        ),
        migrations.RemoveField(
            model_name='movequeue',
            name='filename',
        ),
        migrations.AddField(
            model_name='movequeue',
            name='torrent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='queue', to='application.torrent'),
        ),
    ]
