# Generated by Django 3.1.2 on 2020-11-12 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0011_auto_20201112_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movequeue',
            name='torrent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queue', to='application.torrent'),
        ),
    ]
